CREATE database IF NOT exists movies_db_mySQL_JWT_NB4;
USE movies_db_mySQL_JWT_NB4;

CREATE TABLE IF NOT EXISTS users (
id INT AUTO_INCREMENT PRIMARY KEY,
email VARCHAR(255) NOT NULL UNIQUE,
name VARCHAR(255),
password VARCHAR(255) NOT NULL,
cratedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS categories (
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(255) NOT NULL,
cratedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
userId INT,
constraint fk_categories_user FOREIGN KEY (userId) references users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS movies (
id INT AUTO_INCREMENT PRIMARY KEY,
title VARCHAR(255) NOT NULL,
year INT,
cratedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
categoryId INT,
userId INT,
CONSTRAINT fk_movie_category FOREIGN KEY (categoryId) references categories(id) on delete set null,
CONSTRAINT fk_movie_users FOREIGN KEY (userId) references users(id) on delete set null
);
